device: cuda:0
multi_gpu: false
num_workers: 8
train:
    epochs: 1000
    batch_size: 2
    lr: 1e-4
    save_best: true
    optimizer: Adam
    loss: CenterNet3DLoss
demo:
    # visibility_thres: 1
    topk: 100
    det_thres: 0.2
    nms_thres: 0.9
data:
    transformed: false
    image_root: /home/kiennt/KienNT/research/data/nuScenes/
#     dataset_name: 'v1.0-trainval'
#     meta_data: /home/kiennt/KienNT/research/data/nuScenes/pickle/train_val/meta.pkl
#     train: /home/kiennt/KienNT/research/data/nuScenes/pickle/train_val/train.pkl
#     val: /home/kiennt/KienNT/research/data/nuScenes/pickle/train_val/val.pkl
    dataset_name: 'v1.0-mini'
    meta_data: /home/kiennt/KienNT/research/data/nuScenes/pickle/mini/meta.pkl
    train: /home/kiennt/KienNT/research/data/nuScenes/pickle/mini/train.pkl
    val: /home/kiennt/KienNT/research/data/nuScenes/pickle/mini/val.pkl
    val_config_path: /home/kiennt/KienNT/research/Detectron3D/config/detection_cvpr_2019.json
    resize: 0.5
    rotation_encode: pi_and_minus_pi
    data_loader: NusceneDatasetCenterNet
models:
    - 
        exp: test
        detector_name: CenterNet3Detector
        head_name: CenterNet3D
        backbone_name: mobilenet
        transform: CenterNetTransformer
        eval: false
        save_dir: /home/kiennt/KienNT/research/Detectron3D/exp/mini/mobilenet_fused_r_center/result
        # save_dir: /home/kiennt/KienNT/research/Detectron3D/exp/mobilenet_fused_r_old/result
        # load_model: /home/kiennt/KienNT/research/Detectron3D/exp/mobilenet_fused_r_old/model_61.pth