device: cuda:0
num_workers: 8
epochs: 1000
batch_size: 4
lr: 1e-4
save_best: true
visibility_thres: 1
# aug: false
data:
    dataset_name: 'v1.0-trainval'
    transformed: false
    # image_root: /home/kiennt/KienNT/research/data/nuScenes/
    meta_data: /home/kiennt/KienNT/research/data/nuScenes/pickle/train_val/meta.pkl
    train: /home/kiennt/KienNT/research/data/nuScenes/pickle/train_val/train.pkl
    val: /home/kiennt/KienNT/research/data/nuScenes/pickle/train_val/val.pkl
    val_config_path: /home/kiennt/KienNT/research/nuscenes-devkit/python-sdk/nuscenes/eval/detection/configs/detection_cvpr_2019.json
models:
    - 
        detector_name: centernet3d
        model_name: mobilenet
        eval: false
        save_dir: /home/kiennt/KienNT/research/Detectron3D/exp/centernet3d/mobilenet
#   - 
#     detector_name: fcos3d
#     model_name: mobilenet
#     eval: false
#     save_dir: /home/hotta/kiennt/Detectron3D/exp/mobilenet
#   - 
#     detector_name: fcos3d
#     model_name: resnet101
#     eval: false
#     save_dir: /home/hotta/kiennt/Detectron3D/exp/resnet101
#   - 
#     detector_name: fcos3d
#     model_name: resnet101_dcn
#     eval: false
#     save_dir: /home/hotta/kiennt/Detectron3D/exp/resnet101_dcn
