device: cuda
multi_gpu: true
num_workers: 16
load_eval: true
train:
    epochs: 1000
    batch_size: 48
    lr: 1e-4
    save_best: true
    optimizer: Adam
    loss: CenterNet3DLoss
demo:
    det_thres: 0.5
    nms_thres: 0.5
    topk: 25
data:
    transformed: false
    image_root: ../../data/nuScenes/
    
    dataset_name: 'v1.0-trainval'
    meta_data: ../../data/nuScenes/pickle/train-val/meta.pkl
    train: ../../data/nuScenes/pickle/train-val/train.pkl
    val: ../../data/nuScenes/pickle/train-val/val.pkl
    
    val_config_path: /home/hotta/kiennt/Detectron3D/config/detection_cvpr_2019.json
    resize: 0.5
    rotation_encode: pi_and_minus_pi
    data_loader: NusceneDatasetCenterNet
    aug:
        flip:
            rate: 0.5
models:
  - 
        exp: efficientnet_v2_s
        detector_name: CenterNet3Detector
        head_name: CenterNet3D
        backbone_name: efficientnet_v2_s
        transform: CenterNetTransformer
        fpn: FusedFPN
        eval: false
        save_dir: '../exp/sample'
#         load_model: 'path_to_weight_file'
