device: cuda:0
num_workers: 8
epochs: 1000
batch_size: 4
lr: 1e-4
save_best: true
visibility_thres: 1
# aug: false
data:
    image_root: /home/hotta/kiennt/data/nuScenes/
    meta_data: /home/hotta/kiennt/data/nuScenes/pickle/train_val/meta.pkl
    train: /home/hotta/kiennt/data/nuScenes/pickle/train_val/train.pkl
    val: /home/hotta/kiennt/data/nuScenes/pickle/train_val/val.pkl
models:
  - 
      model_name: mobilenet
      eval: false
      save_dir: /home/hotta/kiennt/Detectron3D/exp/mobilenet
  - 
      model_name: resnet101
      eval: false
      save_dir: /home/hotta/kiennt/Detectron3D/exp/resnet101
  - 
      model_name: resnet101_dcn
      eval: false
      save_dir: /home/hotta/kiennt/Detectron3D/exp/resnet101_dcn
